server:
  port: 8000
spring:
  application:
    name: monitor-service
  cloud:
    zookeeper:
      connect-string: 123.206.64.103:2181
      discovery:
        enabled: true
        root: /monitor
    boot:
      admin:
        client:
          url: "http://localhost:8000"

  # 开放健康检查接口
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS