server:
  port: 8008
spring:
  application:
    name: /order-service
  cloud:
    zookeeper:
      connect-string: 123.206.64.103:2181
      discovery:
        enabled: true
        root: /spring-cloud-service
  boot:
    admin:
      client:
        url: "http://localhost:8000"

# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
